// [문제 링크]: https://school.programmers.co.kr/learn/courses/30/lessons/144854

-- 코드를 입력하세요
SELECT BOOK_ID,AUTHOR_NAME,DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK LEFT JOIN AUTHOR
ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE BOOK.CATEGORY = '경제'
ORDER BY DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') ASC